<?xml version="1.0"?>
<package format="3">
  <name>pongbot_navigation</name>
  <version>0.0.0</version>
  <description>Navigation stack for Pongbot on ROS2/Nav2</description>

  <maintainer email="kim@todo.todo">kim</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_core</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>nav2_util</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <depend>rubi_heightmap_wavefront_planner</depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>

  <exec_depend>nav2_mppi_controller</exec_depend>
  <exec_depend>spatio_temporal_voxel_layer</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>lifecycle_msgs</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>sensor_msgs_py</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <nav2_core plugin="${prefix}/plugins.xml"/>
  </export>
</package>
