DWAPlannerROS:
  # Velocity Limits (TEB와 유사하게 낮춤)
  max_vel_x: 0.8
  min_vel_x: 0.0            # 후진 금지에 가깝게(필요시 -0.02로 아주 약한 후진 허용)
  max_vel_theta: 2.0
  min_vel_theta: -2.5       # 회전은 양/음 모두 허용

  max_vel_y: 0.0
  min_vel_y: 0.0

  # Y 방향 행동 막기
  
  
  holonomic_robot: false

  # in-place 회전을 확실히 하려면 이거 꼭 넣어라
  min_in_place_vel_theta: 0.4   # 너무 낮으면 못 돌고, 너무 높으면 휙 돎(0.3~0.6에서 시작)

  # Acc limits (TEB와 비슷하게 낮춤)
  acc_lim_x: 2.0
  acc_lim_th: 2.0
  acc_lim_y: 0.0

  # Simulation
  sim_time: 1.0            # 빠른 후보가 충돌로 탈락하는 것을 막으려면 sim_time을 막아서 time_horizon을 짧게
  vx_samples: 20            # sample 좀 더 많이 (8 -> 20)
  vy_samples: 1
  vth_samples: 30
  sim_granularity: 0.025
  angular_sim_granularity: 0.025

  # Costs (path/goal/obstacle 밸런스)
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.08             # 0.02는 장애물 회피가 약해서 벽 붙거나, 반대로 costmap 노이즈면 흔들릴 수 있음(0.03~0.1 튜닝)
  forward_point_distance: 0.6     # 앞쪽 어느 지점을 바라보느냐?? / 작으면 각속도 반응 예민, 컨트롤러 흔들리기 쉬움
  stop_time_buffer: 0.2
  prune_plan: true
  transform_tolerance: 0.3

  # Goal reach behavior: stop -> rotate in place 유도
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.20
  latch_xy_goal_tolerance: true
