# global_costmap:
#   # global_frame: map
#   global_frame: map_2d
#   # robot_base_frame: BODY
#   # robot_base_frame: base_footprint
#   robot_base_frame: body
#   update_frequency: 1.0         # The frequency in Hz for the map to be updated.
#   publish_frequency: 1.0        # The frequency in Hz for the map to be publish display information.
#   resolution: 0.05              # 5cm resolution
#   static_map: true              # Use static map
#   rolling_window: false         # For the robot to be center, move
#   transform_tolerance: 0.5      # As same as AMCL transform_tolerance, 0.5 -> 1.0 여유마진 주기

#   plugins:
#     - {name: static_map, type: "costmap_2d::StaticLayer"}
#     - {name: inflation, type: "costmap_2d::InflationLayer"}

#   inflation:
#     inflation_radius: 0.80
#     cost_scaling_factor: 2.0
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link

      update_frequency: 2.0
      publish_frequency: 1.0

      # 디버깅이 끝나면 false
      always_send_full_costmap: false

      resolution: 0.05
      track_unknown_space: true
      rolling_window: false
      transform_tolerance: 1.0
      robot_radius: 0.25

      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        map_topic: /map

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 3.0