global_costmap:
  # global_frame: map
  global_frame: map_2d
  # robot_base_frame: BODY
  # robot_base_frame: base_footprint
  robot_base_frame: body
  update_frequency: 5.0         # The frequency in Hz for the map to be updated.
  publish_frequency: 3.0        # The frequency in Hz for the map to be publish display information.
  resolution: 0.1              # 5cm resolution
  static_map: true              # Use static map
  rolling_window: false         # For the robot to be center, move
  transform_tolerance: 1.0      # As same as AMCL transform_tolerance, 0.5 -> 1.0 여유마진 주기

  plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    # - {name: obstacles, type: "costmap_2d::ObstacleLayer"}        # global 측면에서 obstacle을 볼 것인가??
    - {name: inflation, type: "costmap_2d::InflationLayer"}
    

  inflation:
    inflation_radius: 0.30
    cost_scaling_factor: 10.0

  obstacles:
    observation_sources: laser
    laser:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      obstacle_range: 4.0
      raytrace_range: 4.5
      min_obstacle_height: 0.0
      max_obstacle_height: 1.8
      observation_persistence: 0.2
      expected_update_rate: 0.0